name: the_meeple
description: The Meeple

dependencies:
  rxdart: ^0.19.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  sqflite: 0.12.2+1
  shared_preferences: ^0.4.3
  path_provider: ^0.4.1
  intl: 0.15.7
  flutter_slidable: ^0.4.9
  image_picker: ^0.5.0+9

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


  assets:
    - assets/images/img_score.png
    - assets/images/img_player.png
    - assets/images/ic_tabbar_score_grey.png
    - assets/images/ic_tabbar_score_blue.png
    - assets/images/ic_tabbar_record_grey.png
    - assets/images/ic_tabbar_record_blue.png
    - assets/images/ic_tabbar_timer_grey.png
    - assets/images/ic_tabbar_timer_blue.png
    - assets/images/ic_tabbar_more_grey.png
    - assets/images/ic_tabbar_more_blue.png
    - assets/images/ic_tabbar_players_grey.png
    - assets/images/ic_tabbar_players_blue.png
    - assets/images/btn_add.png
    - assets/images/btn_added.png
    - assets/images/ic_add.png
    - assets/images/ic_add_blue.png
    - assets/images/ic_manage.png
    - assets/images/ic_close.png
    - assets/images/chevron_right.png
    - assets/images/ic_action_save.png
    - assets/images/ic_action_reset.png
    - assets/images/ic_action_startnew.png
    - assets/images/ic_action_rank.png
    - assets/images/ic_action_add.png
    - assets/images/ic_manage.png
    - assets/images/ic_search.png
    - assets/images/ic_manage.png
    - assets/images/ic_toast_dismiss.png
    - assets/images/ic_delete_bin.png
    - assets/images/ic_record_share.png
    - assets/images/img_bbg_small.png
    - assets/images/img_record_home.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/manrope-bold.otf
        - asset: fonts/manrope-extrabold.otf
          weight: 900

